In [2]:
import pandas as pd

In [4]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\20101\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\20101\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
customers = pd.read_csv('Customers.xlsx', sep=',', encoding='latin1')
products = pd.read_csv('Products.xlsx', sep=',', encoding='latin1')
sales = pd.read_csv('Sales.xlsx', sep=',', encoding='latin1')
exchange_rates = pd.read_csv('Exchange_Rates.xlsx', sep=',', encoding='latin1')

In [10]:
for df in [customers, products, sales, exchange_rates]:df.columns=df.columns.str.strip()

In [12]:
print(products.head(10))

   ProductKey                         Product Name    Brand   Color  \
0           1  Contoso 512MB MP3 Player E51 Silver  Contoso  Silver
1           2    Contoso 512MB MP3 Player E51 Blue  Contoso    Blue
2           3     Contoso 1G MP3 Player E100 White  Contoso   White
3           4    Contoso 2G MP3 Player E200 Silver  Contoso  Silver
4           5       Contoso 2G MP3 Player E200 Red  Contoso     Red
5           6     Contoso 2G MP3 Player E200 Black  Contoso   Black
6           7      Contoso 2G MP3 Player E200 Blue  Contoso    Blue
7           8    Contoso 4G MP3 Player E400 Silver  Contoso  Silver
8           9     Contoso 4G MP3 Player E400 Black  Contoso   Black
9          10     Contoso 4G MP3 Player E400 Green  Contoso   Green

  Unit Cost USD Unit Price USD  SubcategoryKey Subcategory  CategoryKey  \
0        $6.62         $12.99              101     MP4&MP3            1
1        $6.62         $12.99              101     MP4&MP3            1
2        $7.40         $14.52              101     MP4&MP3            1
3       $11.00         $21.57              101     MP4&MP3            1
4       $11.00         $21.57              101     MP4&MP3            1
5       $11.00         $21.57              101     MP4&MP3            1
6       $11.00         $21.57              101     MP4&MP3            1
7       $30.58         $59.99              101     MP4&MP3            1
8       $30.58         $59.99              101     MP4&MP3            1
9       $30.58         $59.99              101     MP4&MP3            1

  Category
0    Audio
1    Audio
2    Audio
3    Audio
4    Audio
5    Audio
6    Audio
7    Audio
8    Audio
9    Audio

In [13]:
sales_enriched=pd.merge(sales,products,on='ProductKey',how='left')

In [15]:
products.head(10)

,ProductKey,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,$6.62,$12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,$6.62,$12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,$7.40,$14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,$11.00,$21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,$11.00,$21.57,101,MP4&MP3,1,Audio
5,6,Contoso 2G MP3 Player E200 Black,Contoso,Black,$11.00,$21.57,101,MP4&MP3,1,Audio
6,7,Contoso 2G MP3 Player E200 Blue,Contoso,Blue,$11.00,$21.57,101,MP4&MP3,1,Audio
7,8,Contoso 4G MP3 Player E400 Silver,Contoso,Silver,$30.58,$59.99,101,MP4&MP3,1,Audio
8,9,Contoso 4G MP3 Player E400 Black,Contoso,Black,$30.58,$59.99,101,MP4&MP3,1,Audio
9,10,Contoso 4G MP3 Player E400 Green,Contoso,Green,$30.58,$59.99,101,MP4&MP3,1,Audio

In [17]:
exchange_rates.head(10)

       Date Currency  Exchange
0  1/1/2015      USD    1.0000
1  1/1/2015      CAD    1.1583
2  1/1/2015      AUD    1.2214
3  1/1/2015      EUR    0.8237
4  1/1/2015      GBP    0.6415
5  1/2/2015      USD    1.0000
6  1/2/2015      CAD    1.1682
7  1/2/2015      AUD    1.2323
8  1/2/2015      EUR    0.8304
9  1/2/2015      GBP    0.6477

In [18]:
sales_enriched.head(10)

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code,Product Name,Brand,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD,Contoso Lens Adapter M450 White,Contoso,White,$31.27,$68.00,406,Cameras & Camcorders Accessories,4,Cameras and camcorders
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD,A. Datum SLR Camera X136 Silver,A. Datum,Silver,$141.47,$427.00,402,Digital SLR Cameras,4,Cameras and camcorders
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD,Fabrikam Microwave 1.5CuFt X1100 Black,Fabrikam,Black,$220.64,$665.94,803,Microwaves,8,Home Appliances
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD,Contoso SLR Camera M146 Orange,Contoso,Orange,$148.08,$322.00,402,Digital SLR Cameras,4,Cameras and camcorders
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD,Adventure Works Laptop8.9 E0890 White,Adventure Works,White,$166.20,$326.00,301,Laptops,3,Computers
5,366002,3,1/1/2016,1/12/2016,266019,0,1080,4,CAD,Contoso SLR Camera X143 Silver,Contoso,Silver,$214.03,$646.00,402,Digital SLR Cameras,4,Cameras and camcorders
6,366004,1,1/1/2016,NaN,1107461,38,163,6,GBP,"Adventure Works 52"" LCD HDTV X790W White",Adventure Works,White,$527.53,"$1,592.20",201,Televisions,2,TV and Video
7,366004,2,1/1/2016,NaN,1107461,38,1529,2,GBP,The Phone Company PDA Handheld 3.5 inch M610 B...,The Phone Company,Black,$117.27,$255.00,504,Smart phones & PDAs,5,Cell phones
8,366005,1,1/1/2016,NaN,844003,33,421,4,EUR,Adventure Works Desktop PC3.0 MS300 Silver,Adventure Works,Silver,$215.68,$469.00,303,Desktops,3,Computers
9,366007,1,1/1/2016,NaN,2035771,43,1617,1,USD,Contoso DVD Player M110 Silver,Contoso,Silver,$26.67,$57.99,602,Movie DVD,6,"Music, Movies and Audio Books"

In [25]:
final_data=pd.merge(sales_enriched,exchange_rates,left_on=['Order Date','Currency Code'],right_on=['Date','Currency'],how='left')

In [26]:
final_data.head(10)

,Order Number,Line Item,Order Date,Delivery Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency Code,Product Name,...,Color,Unit Cost USD,Unit Price USD,SubcategoryKey,Subcategory,CategoryKey,Category,Date,Currency,Exchange
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD,Contoso Lens Adapter M450 White,...,White,$31.27,$68.00,406,Cameras & Camcorders Accessories,4,Cameras and camcorders,1/1/2016,CAD,1.3884
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD,A. Datum SLR Camera X136 Silver,...,Silver,$141.47,$427.00,402,Digital SLR Cameras,4,Cameras and camcorders,1/1/2016,USD,1.0000
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD,Fabrikam Microwave 1.5CuFt X1100 Black,...,Black,$220.64,$665.94,803,Microwaves,8,Home Appliances,1/1/2016,USD,1.0000
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD,Contoso SLR Camera M146 Orange,...,Orange,$148.08,$322.00,402,Digital SLR Cameras,4,Cameras and camcorders,1/1/2016,CAD,1.3884
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD,Adventure Works Laptop8.9 E0890 White,...,White,$166.20,$326.00,301,Laptops,3,Computers,1/1/2016,CAD,1.3884
5,366002,3,1/1/2016,1/12/2016,266019,0,1080,4,CAD,Contoso SLR Camera X143 Silver,...,Silver,$214.03,$646.00,402,Digital SLR Cameras,4,Cameras and camcorders,1/1/2016,CAD,1.3884
6,366004,1,1/1/2016,NaN,1107461,38,163,6,GBP,"Adventure Works 52"" LCD HDTV X790W White",...,White,$527.53,"$1,592.20",201,Televisions,2,TV and Video,1/1/2016,GBP,0.6742
7,366004,2,1/1/2016,NaN,1107461,38,1529,2,GBP,The Phone Company PDA Handheld 3.5 inch M610 B...,...,Black,$117.27,$255.00,504,Smart phones & PDAs,5,Cell phones,1/1/2016,GBP,0.6742
8,366005,1,1/1/2016,NaN,844003,33,421,4,EUR,Adventure Works Desktop PC3.0 MS300 Silver,...,Silver,$215.68,$469.00,303,Desktops,3,Computers,1/1/2016,EUR,0.9185
9,366007,1,1/1/2016,NaN,2035771,43,1617,1,USD,Contoso DVD Player M110 Silver,...,Silver,$26.67,$57.99,602,Movie DVD,6,"Music, Movies and Audio Books",1/1/2016,USD,1.0000

In [27]:
final_data = pd.merge(final_data, customers, on='CustomerKey', how='left')

In [28]:
final_data.columns = [col.replace(' ', '_') for col in final_data.columns]

In [29]:
final_data.head(10)

,Order_Number,Line_Item,Order_Date,Delivery_Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency_Code,Product_Name,...,Exchange,Gender,Name,City,State_Code,State,Zip_Code,Country,Continent,Birthday
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD,Contoso Lens Adapter M450 White,...,1.3884,Male,Tyler Vaught,London,ON,Ontario,N5W 5K6,Canada,North America,3/23/1971
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD,A. Datum SLR Camera X136 Silver,...,1.0000,Male,Frank Upchurch,Auberry,CA,California,93602,United States,North America,11/20/1995
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD,Fabrikam Microwave 1.5CuFt X1100 Black,...,1.0000,Male,Frank Upchurch,Auberry,CA,California,93602,United States,North America,11/20/1995
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD,Contoso SLR Camera M146 Orange,...,1.3884,Female,Joan Roche,Red Deer,AB,Alberta,T4N 2A6,Canada,North America,8/24/1962
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD,Adventure Works Laptop8.9 E0890 White,...,1.3884,Female,Joan Roche,Red Deer,AB,Alberta,T4N 2A6,Canada,North America,8/24/1962
5,366002,3,1/1/2016,1/12/2016,266019,0,1080,4,CAD,Contoso SLR Camera X143 Silver,...,1.3884,Female,Joan Roche,Red Deer,AB,Alberta,T4N 2A6,Canada,North America,8/24/1962
6,366004,1,1/1/2016,NaN,1107461,38,163,6,GBP,"Adventure Works 52"" LCD HDTV X790W White",...,0.6742,Male,Sam Nelson,BURSCOUGH BRIDGE,West Lancashire,West Lancashire,L40 8UX,United Kingdom,Europe,11/28/1979
7,366004,2,1/1/2016,NaN,1107461,38,1529,2,GBP,The Phone Company PDA Handheld 3.5 inch M610 B...,...,0.6742,Male,Sam Nelson,BURSCOUGH BRIDGE,West Lancashire,West Lancashire,L40 8UX,United Kingdom,Europe,11/28/1979
8,366005,1,1/1/2016,NaN,844003,33,421,4,EUR,Adventure Works Desktop PC3.0 MS300 Silver,...,0.9185,Male,Ouassim Heuver,Leeuwarden,FR,Friesland,8916 CD,Netherlands,Europe,6/22/1995
9,366007,1,1/1/2016,NaN,2035771,43,1617,1,USD,Contoso DVD Player M110 Silver,...,1.0000,Female,Damiana Corona,Winchester,VA,Virginia,22601,United States,North America,10/30/1944

In [35]:
cols_to_fix = ['Quantity', 'Unit_Price_USD', 'Unit_Cost_USD', 'Exchange']
for col in cols_to_fix:
    final_data[col] = pd.to_numeric(final_data[col].astype(str).str.replace(r'[^\d.]', '', regex=True), errors='coerce')
final_data[cols_to_fix] = final_data[cols_to_fix].fillna(0)

In [38]:
final_data['Total_Revenue_USD'] = final_data['Quantity'] * final_data['Unit_Price_USD'] * final_data['Exchange']
final_data['Total_Cost_USD'] = final_data['Quantity'] * final_data['Unit_Cost_USD'] * final_data['Exchange']
final_data['Profit_USD'] = final_data['Total_Revenue_USD'] - final_data['Total_Cost_USD']

In [40]:
final_data[['Total_Revenue_USD','Total_Cost_USD','Profit_USD']].head(10)

   Total_Revenue_USD  Total_Cost_USD   Profit_USD
0           94.41120       43.415268    50.995932
1          854.00000      282.940000   571.060000
2          665.94000      220.640000   445.300000
3         3129.45360     1439.159904  1690.293696
4          452.61840      230.752080   221.866320
5         3587.62560     1188.637008  2398.988592
6         6440.76744     2133.964356  4306.803084
7          343.84200      158.126868   185.715132
8         1723.10600      792.408320   930.697680
9           57.99000       26.670000    31.320000

In [30]:
final_data.duplicated().sum()

np.int64(0)

In [32]:
final_data.isnull().sum()

Order_Number          0
Line_Item             0
Order_Date            0
Delivery_Date     49719
CustomerKey           0
StoreKey              0
ProductKey            0
Quantity              0
Currency_Code         0
Product_Name          0
Brand                 0
Color                 0
Unit_Cost_USD         0
Unit_Price_USD        0
SubcategoryKey        0
Subcategory           0
CategoryKey           0
Category              0
Date                  0
Currency              0
Exchange              0
Gender                0
Name                  0
City                  0
State_Code           30
State                 0
Zip_Code              0
Country               0
Continent             0
Birthday              0
dtype: int64

In [41]:
final_data['Delivery_Date']=final_data['Delivery_Date'].fillna('Not Shipped Yet')
final_data['State_Code'] = final_data['State_Code'].fillna('N/A')

In [42]:
final_data.isnull().sum()

Order_Number         0
Line_Item            0
Order_Date           0
Delivery_Date        0
CustomerKey          0
StoreKey             0
ProductKey           0
Quantity             0
Currency_Code        0
Product_Name         0
Brand                0
Color                0
Unit_Cost_USD        0
Unit_Price_USD       0
SubcategoryKey       0
Subcategory          0
CategoryKey          0
Category             0
Date                 0
Currency             0
Exchange             0
Gender               0
Name                 0
City                 0
State_Code           0
State                0
Zip_Code             0
Country              0
Continent            0
Birthday             0
Total_Revenue_USD    0
Total_Cost_USD       0
Profit_USD           0
dtype: int64

In [43]:
final_data.to_csv('Global_Sales_Clean_Final.csv', index=False)

In [45]:
print(final_data.head(10))

   Order_Number  Line_Item Order_Date    Delivery_Date  CustomerKey  StoreKey  \
0        366000          1   1/1/2016  Not Shipped Yet       265598        10
1        366001          1   1/1/2016        1/13/2016      1269051         0
2        366001          2   1/1/2016        1/13/2016      1269051         0
3        366002          1   1/1/2016        1/12/2016       266019         0
4        366002          2   1/1/2016        1/12/2016       266019         0
5        366002          3   1/1/2016        1/12/2016       266019         0
6        366004          1   1/1/2016  Not Shipped Yet      1107461        38
7        366004          2   1/1/2016  Not Shipped Yet      1107461        38
8        366005          1   1/1/2016  Not Shipped Yet       844003        33
9        366007          1   1/1/2016  Not Shipped Yet      2035771        43

   ProductKey  Quantity Currency_Code  \
0        1304         1           CAD
1        1048         2           USD
2        2007         1           USD
3        1106         7           CAD
4         373         1           CAD
5        1080         4           CAD
6         163         6           GBP
7        1529         2           GBP
8         421         4           EUR
9        1617         1           USD

                                        Product_Name  ...              City  \
0                    Contoso Lens Adapter M450 White  ...            London
1                    A. Datum SLR Camera X136 Silver  ...           Auberry
2             Fabrikam Microwave 1.5CuFt X1100 Black  ...           Auberry
3                     Contoso SLR Camera M146 Orange  ...          Red Deer
4              Adventure Works Laptop8.9 E0890 White  ...          Red Deer
5                     Contoso SLR Camera X143 Silver  ...          Red Deer
6           Adventure Works 52" LCD HDTV X790W White  ...  BURSCOUGH BRIDGE
7  The Phone Company PDA Handheld 3.5 inch M610 B...  ...  BURSCOUGH BRIDGE
8         Adventure Works Desktop PC3.0 MS300 Silver  ...        Leeuwarden
9                     Contoso DVD Player M110 Silver  ...        Winchester

        State_Code            State  Zip_Code         Country      Continent  \
0               ON          Ontario   N5W 5K6          Canada  North America
1               CA       California     93602   United States  North America
2               CA       California     93602   United States  North America
3               AB          Alberta   T4N 2A6          Canada  North America
4               AB          Alberta   T4N 2A6          Canada  North America
5               AB          Alberta   T4N 2A6          Canada  North America
6  West Lancashire  West Lancashire   L40 8UX  United Kingdom         Europe
7  West Lancashire  West Lancashire   L40 8UX  United Kingdom         Europe
8               FR        Friesland   8916 CD     Netherlands         Europe
9               VA         Virginia     22601   United States  North America

     Birthday Total_Revenue_USD Total_Cost_USD   Profit_USD
0   3/23/1971          94.41120      43.415268    50.995932
1  11/20/1995         854.00000     282.940000   571.060000
2  11/20/1995         665.94000     220.640000   445.300000
3   8/24/1962        3129.45360    1439.159904  1690.293696
4   8/24/1962         452.61840     230.752080   221.866320
5   8/24/1962        3587.62560    1188.637008  2398.988592
6  11/28/1979        6440.76744    2133.964356  4306.803084
7  11/28/1979         343.84200     158.126868   185.715132
8   6/22/1995        1723.10600     792.408320   930.697680
9  10/30/1944          57.99000      26.670000    31.320000

[10 rows x 33 columns]

In [46]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\20101\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\20101\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\20101\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\20101\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)

In [52]:
import pymysql
import pandas as pd
from sqlalchemy import create_engine

username = "root"
password = "Saied55555#"
host = "localhost"
port = "3306"
database = "retailer_sales"

connection = pymysql.connect(host=host, user=username, password=password)
cursor = connection.cursor()
cursor.execute(f"CREATE DATABASE IF NOT EXISTS {database};")
connection.close()

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")


final_data.to_sql('final_data', engine, if_exists='replace', index=False)
pd.read_sql("SELECT * FROM final_data LIMIT 5;", engine)

,Order_Number,Line_Item,Order_Date,Delivery_Date,CustomerKey,StoreKey,ProductKey,Quantity,Currency_Code,Product_Name,...,City,State_Code,State,Zip_Code,Country,Continent,Birthday,Total_Revenue_USD,Total_Cost_USD,Profit_USD
0,366000,1,1/1/2016,Not Shipped Yet,265598,10,1304,1,CAD,Contoso Lens Adapter M450 White,...,London,ON,Ontario,N5W 5K6,Canada,North America,3/23/1971,94.4112,43.415268,50.995932
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD,A. Datum SLR Camera X136 Silver,...,Auberry,CA,California,93602,United States,North America,11/20/1995,854.0000,282.940000,571.060000
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD,Fabrikam Microwave 1.5CuFt X1100 Black,...,Auberry,CA,California,93602,United States,North America,11/20/1995,665.9400,220.640000,445.300000
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD,Contoso SLR Camera M146 Orange,...,Red Deer,AB,Alberta,T4N 2A6,Canada,North America,8/24/1962,3129.4536,1439.159904,1690.293696
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD,Adventure Works Laptop8.9 E0890 White,...,Red Deer,AB,Alberta,T4N 2A6,Canada,North America,8/24/1962,452.6184,230.752080,221.866320